#ifndef __KSU_UAPI_SELINUX_H
#define __KSU_UAPI_SELINUX_H

#include <linux/types.h>

#define KSU_SEPOLICY_CMD_NORMAL_PERM 1U
#define KSU_SEPOLICY_CMD_XPERM 2U
#define KSU_SEPOLICY_CMD_TYPE_STATE 3U
#define KSU_SEPOLICY_CMD_TYPE 4U
#define KSU_SEPOLICY_CMD_TYPE_ATTR 5U
#define KSU_SEPOLICY_CMD_ATTR 6U
#define KSU_SEPOLICY_CMD_TYPE_TRANSITION 7U
#define KSU_SEPOLICY_CMD_TYPE_CHANGE 8U
#define KSU_SEPOLICY_CMD_GENFSCON 9U

#define KSU_SEPOLICY_SUBCMD_NORMAL_PERM_ALLOW 1U
#define KSU_SEPOLICY_SUBCMD_NORMAL_PERM_DENY 2U
#define KSU_SEPOLICY_SUBCMD_NORMAL_PERM_AUDITALLOW 3U
#define KSU_SEPOLICY_SUBCMD_NORMAL_PERM_DONTAUDIT 4U

#define KSU_SEPOLICY_SUBCMD_XPERM_ALLOW 1U
#define KSU_SEPOLICY_SUBCMD_XPERM_AUDITALLOW 2U
#define KSU_SEPOLICY_SUBCMD_XPERM_DONTAUDIT 3U

#define KSU_SEPOLICY_SUBCMD_TYPE_STATE_PERMISSIVE 1U
#define KSU_SEPOLICY_SUBCMD_TYPE_STATE_ENFORCE 2U

#define KSU_SEPOLICY_SUBCMD_TYPE_CHANGE_CHANGE 1U
#define KSU_SEPOLICY_SUBCMD_TYPE_CHANGE_MEMBER 2U

#endif
